### ISSUE TITLE
Copy of example AWS QLDB vehicle-registration ledger dump

### ISSUE THREAD

**Issue by coffeegoddd** [aws-samples/example-qldb-ledger-migration#1]
I'd like to write a blog about migrating from AWS QLDB to [Dolt](https://www.doltdb.com), but can no longer create ledgers on QLDB... it seems they're only supporting existing customers, not new ones.

Is there anyway you could provide a copy of the `vehicle-registration` ledger dump so I can transform it for a Dolt migration tutorial?

Thanks!

**Comment by aws-dbblaner** [comment]
Hey, coffeegoddd. Submit a case through AWS Support to ask them to allow-list your account(s) for QLDB.  Tell them that you're developing a migration solution for QLDB and that you need to be able to create ledgers for development and testing.  I think this would give you the most flexibility for developing and testing your solution.  If they won't do it, let me know and I'll create a fresh export of the vehicle-registration sample data for you.

**Comment by coffeegoddd** [comment]
Thanks for your response! I'll file a support ticket as you suggested.

**Comment by coffeegoddd** [comment]
@aws-dbblaner I guess AWS Support charges money for the ability to file cases... I didn't realize this. Is there anyway you'd be willing to provide a fresh export in lieu of the support ticket? It would really help me out, and I'd be happy to give you a direct shoutout in the resulting blog.

**Comment by aws-dbblaner** [comment]
Hey, Dustin.  I just messaged you on LinkedIn, too. QLDB creates the sample ledger tables and data all in one transaction, so it makes for a really boring, one-block export. It's better if you're able to access a ledger to create more interesting traffic in your exports:  updates, deletes, read-only transactions, redactions, etc. etc.  I sent info on how we might accomplish this in a LinkedIn message.
